/*
 * generated by XText 2.19.0
 */
package prodest.es.gov.br.dsl.ui;

import com.google.inject.Injector;
import nest_dsl.ui.internal.Nest_dslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NestDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Nest_dslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Nest_dslActivator activator = Nest_dslActivator.getInstance();
		return activator != null ? activator.getInjector(Nest_dslActivator.PRODEST_ES_GOV_BR_DSL_NESTDSL) : null;
	}

}
