/*
 * generated by Xtext 2.18.0.M3
 */
package prodest.es.gov.br.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NestDslRuntimeModule extends AbstractNestDslRuntimeModule {
}
