/*
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import prodest.es.gov.br.dsl.nestdsl.Domainmodel
import static org.junit.Assert.*
import prodest.es.gov.br.dsl.nestdsl.Entity

@ExtendWith(InjectionExtension)
@InjectWith(NestDslInjectorProvider)
class NestDslParsingTest {
	@Inject
	ParseHelper<Domainmodel> parseHelper
	
	 @Test 
    def void parseDomainmodel() {
        val model = parseHelper.parse(
            "entity MyEntity {
                parent: MyEntity
            }")
        val entity = model.elements.head as Entity
        assertSame(entity, entity.properties.head.type)
        
        }
}
