/*
 * generated by XText 2.17.0
 */
package prodest.es.gov.br.dsl.ui.tests;

import com.google.inject.Injector;
import nest_dsl.ui.internal.Nest_dslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class NestDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Nest_dslActivator.getInstance().getInjector("prodest.es.gov.br.dsl.NestDsl");
	}

}
