/**
 * generated by XText 2.19.0
 */
package prodest.es.gov.br.dsl.nestdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.Description#getTextfield <em>Textfield</em>}</li>
 * </ul>
 *
 * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getDescription()
 * @model
 * @generated
 */
public interface Description extends EObject
{
  /**
   * Returns the value of the '<em><b>Textfield</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Textfield</em>' attribute.
   * @see #setTextfield(String)
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getDescription_Textfield()
   * @model
   * @generated
   */
  String getTextfield();

  /**
   * Sets the value of the '{@link prodest.es.gov.br.dsl.nestdsl.Description#getTextfield <em>Textfield</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Textfield</em>' attribute.
   * @see #getTextfield()
   * @generated
   */
  void setTextfield(String value);

} // Description
