/**
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.nestdsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.Dto#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.Dto#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getDto()
 * @model
 * @generated
 */
public interface Dto extends DtoType
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Dto)
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getDto_SuperType()
   * @model
   * @generated
   */
  Dto getSuperType();

  /**
   * Sets the value of the '{@link prodest.es.gov.br.dsl.nestdsl.Dto#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Dto value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link prodest.es.gov.br.dsl.nestdsl.DtoProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getDto_Properties()
   * @model containment="true"
   * @generated
   */
  EList<DtoProperty> getProperties();

} // Dto
