/**
 * generated by XText 2.19.0
 */
package prodest.es.gov.br.dsl.nestdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Arg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getName <em>Name</em>}</li>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getClassType <em>Class Type</em>}</li>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getType <em>Type</em>}</li>
 *   <li>{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getArray <em>Array</em>}</li>
 * </ul>
 *
 * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getMethodArg()
 * @model
 * @generated
 */
public interface MethodArg extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getMethodArg_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Class Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Type</em>' reference.
   * @see #setClassType(AbstractElement)
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getMethodArg_ClassType()
   * @model
   * @generated
   */
  AbstractElement getClassType();

  /**
   * Sets the value of the '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getClassType <em>Class Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Type</em>' reference.
   * @see #getClassType()
   * @generated
   */
  void setClassType(AbstractElement value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getMethodArg_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(String)
   * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getMethodArg_Array()
   * @model
   * @generated
   */
  String getArray();

  /**
   * Sets the value of the '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #getArray()
   * @generated
   */
  void setArray(String value);

} // MethodArg
