/**
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.nestdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see prodest.es.gov.br.dsl.nestdsl.NestdslFactory
 * @model kind="package"
 * @generated
 */
public interface NestdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "nestdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.prodest.es.gov.br/dsl/NestDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "nestdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NestdslPackage eINSTANCE = prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl.init();

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.DomainmodelImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.AbstractElementImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.TypeImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getType()
   * @generated
   */
  int TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DtoTypeImpl <em>Dto Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.DtoTypeImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDtoType()
   * @generated
   */
  int DTO_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_TYPE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Dto Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_TYPE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.EntityImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__PROPERTIES = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__METHODS = TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DtoImpl <em>Dto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.DtoImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDto()
   * @generated
   */
  int DTO = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO__NAME = DTO_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO__SUPER_TYPE = DTO_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO__PROPERTIES = DTO_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Dto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_FEATURE_COUNT = DTO_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.DataTypeImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.PropertyImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 7;

  /**
   * The feature id for the '<em><b>Relation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__RELATION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 2;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__ARRAY = 3;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DtoPropertyImpl <em>Dto Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.DtoPropertyImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDtoProperty()
   * @generated
   */
  int DTO_PROPERTY = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_PROPERTY__TYPE = 1;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_PROPERTY__ARRAY = 2;

  /**
   * The number of structural features of the '<em>Dto Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_PROPERTY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.RelationImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 9;

  /**
   * The feature id for the '<em><b>One Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__ONE_ARGUMENT = 0;

  /**
   * The feature id for the '<em><b>Multiple Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__MULTIPLE_ARGUMENT = 1;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.OneArgumentRelationImpl <em>One Argument Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.OneArgumentRelationImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getOneArgumentRelation()
   * @generated
   */
  int ONE_ARGUMENT_RELATION = 10;

  /**
   * The feature id for the '<em><b>Argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_ARGUMENT_RELATION__ARGUMENT = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_ARGUMENT_RELATION__TYPE = 1;

  /**
   * The number of structural features of the '<em>One Argument Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_ARGUMENT_RELATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.MultipleArgumentRelationImpl <em>Multiple Argument Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.MultipleArgumentRelationImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getMultipleArgumentRelation()
   * @generated
   */
  int MULTIPLE_ARGUMENT_RELATION = 11;

  /**
   * The feature id for the '<em><b>Argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLE_ARGUMENT_RELATION__ARGUMENT = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLE_ARGUMENT_RELATION__TYPE = 1;

  /**
   * The feature id for the '<em><b>Second Argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLE_ARGUMENT_RELATION__SECOND_ARGUMENT = 2;

  /**
   * The number of structural features of the '<em>Multiple Argument Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLE_ARGUMENT_RELATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.MethodImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 12;

  /**
   * The feature id for the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__VERB = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__NAME = 1;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__ARGS = 2;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__RETURN_TYPE = 3;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__ARRAY = 4;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.MethodArgImpl <em>Method Arg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see prodest.es.gov.br.dsl.nestdsl.impl.MethodArgImpl
   * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getMethodArg()
   * @generated
   */
  int METHOD_ARG = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_ARG__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_ARG__TYPE = 1;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_ARG__ARRAY = 2;

  /**
   * The number of structural features of the '<em>Method Arg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_ARG_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link prodest.es.gov.br.dsl.nestdsl.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.AbstractElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.AbstractElement#getName()
   * @see #getAbstractElement()
   * @generated
   */
  EAttribute getAbstractElement_Name();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.DtoType <em>Dto Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dto Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.DtoType
   * @generated
   */
  EClass getDtoType();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link prodest.es.gov.br.dsl.nestdsl.Entity#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Entity#getProperties()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Properties();

  /**
   * Returns the meta object for the containment reference list '{@link prodest.es.gov.br.dsl.nestdsl.Entity#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methods</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Entity#getMethods()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Methods();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Dto <em>Dto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dto</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Dto
   * @generated
   */
  EClass getDto();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.Dto#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Dto#getSuperType()
   * @see #getDto()
   * @generated
   */
  EReference getDto_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link prodest.es.gov.br.dsl.nestdsl.Dto#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Dto#getProperties()
   * @see #getDto()
   * @generated
   */
  EReference getDto_Properties();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the containment reference '{@link prodest.es.gov.br.dsl.nestdsl.Property#getRelation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relation</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Property#getRelation()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Relation();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.Property#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Property#getArray()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Array();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.DtoProperty <em>Dto Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dto Property</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.DtoProperty
   * @generated
   */
  EClass getDtoProperty();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.DtoProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.DtoProperty#getName()
   * @see #getDtoProperty()
   * @generated
   */
  EAttribute getDtoProperty_Name();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.DtoProperty#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.DtoProperty#getType()
   * @see #getDtoProperty()
   * @generated
   */
  EReference getDtoProperty_Type();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.DtoProperty#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.DtoProperty#getArray()
   * @see #getDtoProperty()
   * @generated
   */
  EAttribute getDtoProperty_Array();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the containment reference '{@link prodest.es.gov.br.dsl.nestdsl.Relation#getOneArgument <em>One Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>One Argument</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Relation#getOneArgument()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_OneArgument();

  /**
   * Returns the meta object for the containment reference '{@link prodest.es.gov.br.dsl.nestdsl.Relation#getMultipleArgument <em>Multiple Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Multiple Argument</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Relation#getMultipleArgument()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_MultipleArgument();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation <em>One Argument Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>One Argument Relation</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation
   * @generated
   */
  EClass getOneArgumentRelation();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation#getArgument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Argument</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation#getArgument()
   * @see #getOneArgumentRelation()
   * @generated
   */
  EAttribute getOneArgumentRelation_Argument();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation#getType()
   * @see #getOneArgumentRelation()
   * @generated
   */
  EReference getOneArgumentRelation_Type();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation <em>Multiple Argument Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiple Argument Relation</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation
   * @generated
   */
  EClass getMultipleArgumentRelation();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation#getArgument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Argument</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation#getArgument()
   * @see #getMultipleArgumentRelation()
   * @generated
   */
  EAttribute getMultipleArgumentRelation_Argument();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation#getType()
   * @see #getMultipleArgumentRelation()
   * @generated
   */
  EReference getMultipleArgumentRelation_Type();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation#getSecondArgument <em>Second Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Second Argument</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation#getSecondArgument()
   * @see #getMultipleArgumentRelation()
   * @generated
   */
  EAttribute getMultipleArgumentRelation_SecondArgument();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.Method#getVerb <em>Verb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Verb</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Method#getVerb()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Verb();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.Method#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Method#getName()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Name();

  /**
   * Returns the meta object for the containment reference list '{@link prodest.es.gov.br.dsl.nestdsl.Method#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Method#getArgs()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_Args();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.Method#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Return Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Method#getReturnType()
   * @see #getMethod()
   * @generated
   */
  EReference getMethod_ReturnType();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.Method#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.Method#getArray()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Array();

  /**
   * Returns the meta object for class '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg <em>Method Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Arg</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MethodArg
   * @generated
   */
  EClass getMethodArg();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MethodArg#getName()
   * @see #getMethodArg()
   * @generated
   */
  EAttribute getMethodArg_Name();

  /**
   * Returns the meta object for the reference '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MethodArg#getType()
   * @see #getMethodArg()
   * @generated
   */
  EReference getMethodArg_Type();

  /**
   * Returns the meta object for the attribute '{@link prodest.es.gov.br.dsl.nestdsl.MethodArg#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see prodest.es.gov.br.dsl.nestdsl.MethodArg#getArray()
   * @see #getMethodArg()
   * @generated
   */
  EAttribute getMethodArg_Array();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  NestdslFactory getNestdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.DomainmodelImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.AbstractElementImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_ELEMENT__NAME = eINSTANCE.getAbstractElement_Name();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.TypeImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DtoTypeImpl <em>Dto Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.DtoTypeImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDtoType()
     * @generated
     */
    EClass DTO_TYPE = eINSTANCE.getDtoType();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.EntityImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__PROPERTIES = eINSTANCE.getEntity_Properties();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__METHODS = eINSTANCE.getEntity_Methods();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DtoImpl <em>Dto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.DtoImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDto()
     * @generated
     */
    EClass DTO = eINSTANCE.getDto();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DTO__SUPER_TYPE = eINSTANCE.getDto_SuperType();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DTO__PROPERTIES = eINSTANCE.getDto_Properties();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.DataTypeImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.PropertyImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Relation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__RELATION = eINSTANCE.getProperty_Relation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__ARRAY = eINSTANCE.getProperty_Array();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.DtoPropertyImpl <em>Dto Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.DtoPropertyImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getDtoProperty()
     * @generated
     */
    EClass DTO_PROPERTY = eINSTANCE.getDtoProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DTO_PROPERTY__NAME = eINSTANCE.getDtoProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DTO_PROPERTY__TYPE = eINSTANCE.getDtoProperty_Type();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DTO_PROPERTY__ARRAY = eINSTANCE.getDtoProperty_Array();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.RelationImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>One Argument</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__ONE_ARGUMENT = eINSTANCE.getRelation_OneArgument();

    /**
     * The meta object literal for the '<em><b>Multiple Argument</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__MULTIPLE_ARGUMENT = eINSTANCE.getRelation_MultipleArgument();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.OneArgumentRelationImpl <em>One Argument Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.OneArgumentRelationImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getOneArgumentRelation()
     * @generated
     */
    EClass ONE_ARGUMENT_RELATION = eINSTANCE.getOneArgumentRelation();

    /**
     * The meta object literal for the '<em><b>Argument</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ONE_ARGUMENT_RELATION__ARGUMENT = eINSTANCE.getOneArgumentRelation_Argument();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ONE_ARGUMENT_RELATION__TYPE = eINSTANCE.getOneArgumentRelation_Type();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.MultipleArgumentRelationImpl <em>Multiple Argument Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.MultipleArgumentRelationImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getMultipleArgumentRelation()
     * @generated
     */
    EClass MULTIPLE_ARGUMENT_RELATION = eINSTANCE.getMultipleArgumentRelation();

    /**
     * The meta object literal for the '<em><b>Argument</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLE_ARGUMENT_RELATION__ARGUMENT = eINSTANCE.getMultipleArgumentRelation_Argument();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLE_ARGUMENT_RELATION__TYPE = eINSTANCE.getMultipleArgumentRelation_Type();

    /**
     * The meta object literal for the '<em><b>Second Argument</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLE_ARGUMENT_RELATION__SECOND_ARGUMENT = eINSTANCE.getMultipleArgumentRelation_SecondArgument();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.MethodImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>Verb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__VERB = eINSTANCE.getMethod_Verb();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__NAME = eINSTANCE.getMethod_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__ARGS = eINSTANCE.getMethod_Args();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD__RETURN_TYPE = eINSTANCE.getMethod_ReturnType();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__ARRAY = eINSTANCE.getMethod_Array();

    /**
     * The meta object literal for the '{@link prodest.es.gov.br.dsl.nestdsl.impl.MethodArgImpl <em>Method Arg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see prodest.es.gov.br.dsl.nestdsl.impl.MethodArgImpl
     * @see prodest.es.gov.br.dsl.nestdsl.impl.NestdslPackageImpl#getMethodArg()
     * @generated
     */
    EClass METHOD_ARG = eINSTANCE.getMethodArg();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_ARG__NAME = eINSTANCE.getMethodArg_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_ARG__TYPE = eINSTANCE.getMethodArg_Type();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_ARG__ARRAY = eINSTANCE.getMethodArg_Array();

  }

} //NestdslPackage
