/**
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.nestdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see prodest.es.gov.br.dsl.nestdsl.NestdslPackage#getType()
 * @model
 * @generated
 */
public interface Type extends AbstractElement
{
} // Type
