/**
 * generated by Xtext 2.18.0.M3
 */
package prodest.es.gov.br.dsl.ui.contentassist;

import prodest.es.gov.br.dsl.ui.contentassist.AbstractNestDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class NestDslProposalProvider extends AbstractNestDslProposalProvider {
}
