/**
 * generated by Xtext 2.18.0.M3
 */
package prodest.es.gov.br.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import prodest.es.gov.br.dsl.ui.AbstractNestDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class NestDslUiModule extends AbstractNestDslUiModule {
  public NestDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
