/*
 * generated by XText 2.17.0
 */
package prodest.es.gov.br.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import prodest.es.gov.br.dsl.nestdsl.DataType;
import prodest.es.gov.br.dsl.nestdsl.Domainmodel;
import prodest.es.gov.br.dsl.nestdsl.Entity;
import prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation;
import prodest.es.gov.br.dsl.nestdsl.NestdslPackage;
import prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation;
import prodest.es.gov.br.dsl.nestdsl.Property;
import prodest.es.gov.br.dsl.nestdsl.Relation;
import prodest.es.gov.br.dsl.services.NestDslGrammarAccess;

@SuppressWarnings("all")
public class NestDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private NestDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == NestdslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case NestdslPackage.DATA_TYPE:
				sequence_DataType(context, (DataType) semanticObject); 
				return; 
			case NestdslPackage.DOMAINMODEL:
				sequence_Domainmodel(context, (Domainmodel) semanticObject); 
				return; 
			case NestdslPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case NestdslPackage.MULTIPLE_ARGUMENT_RELATION:
				sequence_MultipleArgumentRelation(context, (MultipleArgumentRelation) semanticObject); 
				return; 
			case NestdslPackage.ONE_ARGUMENT_RELATION:
				sequence_OneArgumentRelation(context, (OneArgumentRelation) semanticObject); 
				return; 
			case NestdslPackage.PROPERTY:
				sequence_Property(context, (Property) semanticObject); 
				return; 
			case NestdslPackage.RELATION:
				sequence_Relation(context, (Relation) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AbstractElement returns DataType
	 *     Type returns DataType
	 *     DataType returns DataType
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_DataType(ISerializationContext context, DataType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, NestdslPackage.Literals.TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, NestdslPackage.Literals.TYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDataTypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Domainmodel returns Domainmodel
	 *
	 * Constraint:
	 *     elements+=AbstractElement+
	 */
	protected void sequence_Domainmodel(ISerializationContext context, Domainmodel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Entity
	 *     Entity returns Entity
	 *     Type returns Entity
	 *
	 * Constraint:
	 *     (name=ID superType=[Entity|QualifiedName]? properties+=Property*)
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MultipleArgumentRelation returns MultipleArgumentRelation
	 *
	 * Constraint:
	 *     ((argument='ManyToOne' | argument='OneToMany') type=[Entity|ID] secondArgument=SECONDARGUMENT)
	 */
	protected void sequence_MultipleArgumentRelation(ISerializationContext context, MultipleArgumentRelation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OneArgumentRelation returns OneArgumentRelation
	 *
	 * Constraint:
	 *     ((argument='OneToOne' | argument='ManyToMany') type=[Entity|ID])
	 */
	protected void sequence_OneArgumentRelation(ISerializationContext context, OneArgumentRelation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Property returns Property
	 *
	 * Constraint:
	 *     (relation=Relation? name=ID type=[Type|QualifiedName] array='[]'?)
	 */
	protected void sequence_Property(ISerializationContext context, Property semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Relation returns Relation
	 *
	 * Constraint:
	 *     (oneArgument=OneArgumentRelation | multipleArgument=MultipleArgumentRelation)
	 */
	protected void sequence_Relation(ISerializationContext context, Relation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
