/*
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import prodest.es.gov.br.dsl.nestdsl.Domainmodel;
import prodest.es.gov.br.dsl.nestdsl.Dto;
import prodest.es.gov.br.dsl.nestdsl.DtoProperty;
import prodest.es.gov.br.dsl.nestdsl.Entity;
import prodest.es.gov.br.dsl.nestdsl.Method;
import prodest.es.gov.br.dsl.nestdsl.MethodArg;
import prodest.es.gov.br.dsl.nestdsl.MultipleArgumentRelation;
import prodest.es.gov.br.dsl.nestdsl.NestdslPackage;
import prodest.es.gov.br.dsl.nestdsl.OneArgumentRelation;
import prodest.es.gov.br.dsl.nestdsl.Property;
import prodest.es.gov.br.dsl.nestdsl.Relation;
import prodest.es.gov.br.dsl.services.NestDslGrammarAccess;

@SuppressWarnings("all")
public class NestDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private NestDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == NestdslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case NestdslPackage.DOMAINMODEL:
				sequence_Domainmodel(context, (Domainmodel) semanticObject); 
				return; 
			case NestdslPackage.DTO:
				sequence_Dto(context, (Dto) semanticObject); 
				return; 
			case NestdslPackage.DTO_PROPERTY:
				sequence_DtoProperty(context, (DtoProperty) semanticObject); 
				return; 
			case NestdslPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case NestdslPackage.METHOD:
				sequence_Method(context, (Method) semanticObject); 
				return; 
			case NestdslPackage.METHOD_ARG:
				sequence_MethodArg(context, (MethodArg) semanticObject); 
				return; 
			case NestdslPackage.MULTIPLE_ARGUMENT_RELATION:
				sequence_MultipleArgumentRelation(context, (MultipleArgumentRelation) semanticObject); 
				return; 
			case NestdslPackage.ONE_ARGUMENT_RELATION:
				sequence_OneArgumentRelation(context, (OneArgumentRelation) semanticObject); 
				return; 
			case NestdslPackage.PROPERTY:
				sequence_Property(context, (Property) semanticObject); 
				return; 
			case NestdslPackage.RELATION:
				sequence_Relation(context, (Relation) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Domainmodel returns Domainmodel
	 *
	 * Constraint:
	 *     elements+=AbstractElement+
	 */
	protected void sequence_Domainmodel(ISerializationContext context, Domainmodel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DtoProperty returns DtoProperty
	 *
	 * Constraint:
	 *     (name=ID (classType=[Dto|QualifiedName] | type=DATATYPE) array='[]'?)
	 */
	protected void sequence_DtoProperty(ISerializationContext context, DtoProperty semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Dto
	 *     Dto returns Dto
	 *
	 * Constraint:
	 *     (name=ID superType=[Dto|QualifiedName]? properties+=DtoProperty*)
	 */
	protected void sequence_Dto(ISerializationContext context, Dto semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractElement returns Entity
	 *     Entity returns Entity
	 *
	 * Constraint:
	 *     (name=ID superType=[Entity|QualifiedName]? properties+=Property* methods+=Method*)
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MethodArg returns MethodArg
	 *
	 * Constraint:
	 *     (name=ID (classType=[AbstractElement|QualifiedName] | type=DATATYPE) array='[]'?)
	 */
	protected void sequence_MethodArg(ISerializationContext context, MethodArg semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Method returns Method
	 *
	 * Constraint:
	 *     (
	 *         (verb='Get' | verb='Post' | verb='Delete' | verb='Put') 
	 *         name=ID 
	 *         args+=MethodArg* 
	 *         (returnClassType=[AbstractElement|QualifiedName] | returnType=DATATYPE) 
	 *         array='[]'?
	 *     )
	 */
	protected void sequence_Method(ISerializationContext context, Method semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     MultipleArgumentRelation returns MultipleArgumentRelation
	 *
	 * Constraint:
	 *     ((argument='ManyToOne' | argument='OneToMany') type=[Entity|ID] secondArgument=ARGUMENTREGEX)
	 */
	protected void sequence_MultipleArgumentRelation(ISerializationContext context, MultipleArgumentRelation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OneArgumentRelation returns OneArgumentRelation
	 *
	 * Constraint:
	 *     ((argument='OneToOne' | argument='ManyToMany') type=[Entity|ID])
	 */
	protected void sequence_OneArgumentRelation(ISerializationContext context, OneArgumentRelation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Property returns Property
	 *
	 * Constraint:
	 *     (relation=Relation? name=ID (classType=[Entity|QualifiedName] | type=DATATYPE) array='[]'?)
	 */
	protected void sequence_Property(ISerializationContext context, Property semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Relation returns Relation
	 *
	 * Constraint:
	 *     (oneArgument=OneArgumentRelation | multipleArgument=MultipleArgumentRelation)
	 */
	protected void sequence_Relation(ISerializationContext context, Relation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
