/**
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.scoping;

import prodest.es.gov.br.dsl.scoping.AbstractNestDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class NestDslScopeProvider extends AbstractNestDslScopeProvider {
}
