/**
 * generated by XText 2.18.0.M3
 */
package prodest.es.gov.br.dsl.validation;

import prodest.es.gov.br.dsl.validation.AbstractNestDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class NestDslValidator extends AbstractNestDslValidator {
}
