/*
 * generated by XText 2.19.0
 */
package prodest.es.gov.br.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractNestDslScopeProvider extends DelegatingScopeProvider {
}
