/*
 * generated by Xtext 2.17.0
 */
package org.example.domainmodel.ui;

import com.google.inject.Injector;
import nest_dsl.ui.internal.Nest_dslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Nest_dslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Nest_dslActivator activator = Nest_dslActivator.getInstance();
		return activator != null ? activator.getInjector(Nest_dslActivator.ORG_EXAMPLE_DOMAINMODEL_DOMAINMODEL) : null;
	}

}
