/**
 * generated by XText 2.17.0
 */
package prodest.es.gov.br.dsl.nestdsl.impl;

import org.eclipse.emf.ecore.EClass;

import prodest.es.gov.br.dsl.nestdsl.DataType;
import prodest.es.gov.br.dsl.nestdsl.NestdslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataTypeImpl extends TypeImpl implements DataType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NestdslPackage.Literals.DATA_TYPE;
  }

} //DataTypeImpl
