/**
 * generated by Xtext 2.18.0.M3
 */
package prodest.es.gov.br.dsl;

import prodest.es.gov.br.dsl.NestDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class NestDslStandaloneSetup extends NestDslStandaloneSetupGenerated {
  public static void doSetup() {
    new NestDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
