/**
 * generated by Xtext 2.18.0.M3
 */
package prodest.es.gov.br.dsl;

import prodest.es.gov.br.dsl.AbstractNestDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class NestDslRuntimeModule extends AbstractNestDslRuntimeModule {
}
